// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaqOYuK4JBZogNygqw61MoZipZun1U5Aw',
    appId: '1:950709413936:web:d156ea455dbb375d2ba5f5',
    messagingSenderId: '950709413936',
    projectId: 'app-distribution-9a4cd',
    authDomain: 'app-distribution-9a4cd.firebaseapp.com',
    storageBucket: 'app-distribution-9a4cd.firebasestorage.app',
    measurementId: 'G-173S3KEQ2N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbsjCRBdbtTCoX3R8QS51c5eH6DuDiLlk',
    appId: '1:950709413936:android:b92210d52f75a1522ba5f5',
    messagingSenderId: '950709413936',
    projectId: 'app-distribution-9a4cd',
    storageBucket: 'app-distribution-9a4cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc-7kVYGc15tn14sEKMWxeX2ZH4HIt_6A',
    appId: '1:950709413936:ios:1904987c7ac9f5ab2ba5f5',
    messagingSenderId: '950709413936',
    projectId: 'app-distribution-9a4cd',
    storageBucket: 'app-distribution-9a4cd.firebasestorage.app',
    iosBundleId: 'com.example.tallerSegundoPlano',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc-7kVYGc15tn14sEKMWxeX2ZH4HIt_6A',
    appId: '1:950709413936:ios:1904987c7ac9f5ab2ba5f5',
    messagingSenderId: '950709413936',
    projectId: 'app-distribution-9a4cd',
    storageBucket: 'app-distribution-9a4cd.firebasestorage.app',
    iosBundleId: 'com.example.tallerSegundoPlano',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaqOYuK4JBZogNygqw61MoZipZun1U5Aw',
    appId: '1:950709413936:web:add3572c974073462ba5f5',
    messagingSenderId: '950709413936',
    projectId: 'app-distribution-9a4cd',
    authDomain: 'app-distribution-9a4cd.firebaseapp.com',
    storageBucket: 'app-distribution-9a4cd.firebasestorage.app',
    measurementId: 'G-Z93GZ074DR',
  );
}
